# Generated by Django 5.2.8 on 2025-12-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок/Модель авто')),
                ('description', models.TextField(verbose_name='Описание работы')),
                ('video_file', models.FileField(upload_to='works/videos/', verbose_name='Видеофайл работы')),
                ('tags', models.CharField(max_length=255, verbose_name='Теги (через запятую, напр: Керамика, Полировка)')),
                ('duration', models.CharField(max_length=50, verbose_name='Срок выполнения (напр: 3 дня)')),
                ('price', models.CharField(max_length=50, verbose_name='Стоимость (напр: от 35 000 руб.)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
        ),
    ]
