# Generated by Django 5.2.8 on 2025-12-04 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='video_file',
        ),
        migrations.AddField(
            model_name='work',
            name='main_media',
            field=models.FileField(blank=True, null=True, upload_to='works/main_media/', verbose_name='Главное фото/видео для карточки'),
        ),
        migrations.AddField(
            model_name='work',
            name='slug',
            field=models.SlugField(default='temp-slug', max_length=255, unique=True, verbose_name='URL-адрес (Slug)'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WorkMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='works/gallery/%Y/%m/%d/', verbose_name='Медиафайл')),
                ('is_image', models.BooleanField(default=True, verbose_name='Это фото?')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='core.work', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Дополнительный медиафайл',
                'verbose_name_plural': 'Дополнительные медиафайлы',
            },
        ),
    ]
