# Generated by Django 5.2.8 on 2025-12-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги/товара')),
                ('category', models.CharField(default='Общее', max_length=100, verbose_name='Категория')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (руб.)')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_images/', verbose_name='Фотография')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL-идентификатор')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступно для записи/заказа')),
            ],
            options={
                'verbose_name': 'Услуга/Товар',
                'verbose_name_plural': 'Услуги и Товары',
                'ordering': ['category', 'name'],
            },
        ),
    ]
